# yamllint disable rule:line-length
---
collections:
  - name: community.general
    version: 8.0.2

  - name: vyos.vyos
    version: 4.1.0

  - name: community.hashi_vault
    src: git+https://github.com/ansible-collections/community.hashi_vault
    version: 6.0.0

  - src: git+https://github.com/prometheus-community/ansible.git
    name: prometheus.prometheus
    version: 0.8.0

  - src: git+https://github.com/napalm-automation/napalm-ansible.git
    name: napalm.napalm
    version: 0.9.13

roles:
  - name: cri.bootstrap
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/bootstrap.git
    version: 0.1.0
  - name: cri.ceph_tools
    src: git+https://gitlab.com/rootmout/ceph_tools.git
    version: 2b76d52deb622a10d4d11a7e86ac0f02388b5f70
  - name: cri.common
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/common.git
    version: a30b138204f2dd0f0f99a8826e8ea02557fa3e30
  - name: cri.docker
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/docker.git
    version: 0.2.0
  - name: cri.gitlab_runner
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/gitlab_runner.git
    version: 0.1.1
  - name: cri.maas_worker
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/maas_worker.git
    version: 0.1.2
  - name: cri.minio_docker
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/minio_docker.git
    version: 0.1.0
  - name: cri.netdata
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/netdata.git
    version: 0.1.1
  - name: cri.network
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/network.git
    version: 0.1.0
  - name: cri.nftables
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/nftables.git
    version: 0.1.0
  - name: cri.promtail
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/promtail.git
    version: 0.1.1
  - name: cri.restic
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/restic.git
    version: 1.4.1
  - name: cri.warsow
    src: git+https://gitlab.cri.epita.fr/cri/iac/ansible/roles/warsow.git
    version: 0.1.1

    # See https://github.com/bertvv/ansible-role-bind/pull/166
  - name: bertvv.bind
    src: git+https://github.com/rissson/ansible-role-bind.git
    version: 40e042189a94759b9780376ff4abfac057cd7016
  - name: bertvv.dhcp
    src: git+https://github.com/bertvv/ansible-role-dhcp.git
    version: ce587ed69afb28d945d5857556ab1661c1bfbe9a
  - name: ckaserer.tftp
    version: 2.1.3
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: cloudalchemy.pushgateway
    version: 0.2.4
  - name: evrardjp.keepalived
    version: 5.1.0
  - name: geerlingguy.nfs
    version: 2.0.0
  - name: mrlesmithjr.chrony
    src: https://github.com/mrlesmithjr/ansible-chrony.git
    version: v0.1.3
  - name: mrlesmithjr.drbd
    src: git+https://github.com/mrlesmithjr/ansible-drbd.git
    version: 2876fa5e70ffe57007125c01baf4848978eba29c
  - name: mrlesmithjr.squid
    version: v0.1.0
  - name: ome.haproxy
    version: 3.2.3
  - name: stackhpc.libvirt-host
    version: v1.8.3
  - name: stackhpc.libvirt-vm
    version: v1.14.2
  - name: timorunge.sssd
    version: 0.5.5

  - src: https://github.com/ansible-community/ansible-vault.git
    name: ansible-community.ansible-vault
    scm: git
    version: c723ec5e3e068a90b316162d19ef2269f99dc11b

  - src: https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-wireguard-cloud-gateway.git
    name: consensus.wireguard_cloud_gateway
    scm: git
    version: 523a89f365915534e0cf0a240341c9b110363c7b

  - src: git+https://github.com/mrlesmithjr/ansible-netplan
    name: mrlesmithjr.netplan
    version: e3f748337a01452d8114abbcf17c913b7de8ac7e

  - src: git+https://github.com/rootmout/ansible-consul.git
    name: ansible-consul
    version: 4f6dd3be48d53049f283b7555284de1f69b13946

  - src: git+https://github.com/Oefenweb/ansible-dnsmasq.git
    name: oefenweb.dnsmasq
    version: 79ddf4503a6e27e7fdcc1017477c7bb3c868a0d6

  - src: git+https://github.com/maxhoesel/ansible-role-ddclient.git
    name: maxhoesel.ddclient
    version: ed970b2c6f6050fa712c22cd1fdcb78f73718e61

  - src: git+https://github.com/mrlesmithjr/ansible-manage-lvm.git
    name: mrlesmithjr.lvm
    version: ea2e60f04388147ca2cf3c87895032b1faf40677

  - src: git+https://github.com/mrlesmithjr/ansible-mdadm
    name: mrlesmithjr.mdadm
    version: a0ee021fa2c2d3e9f47b77f909b6210db52dad92

  - src: git+https://github.com/mrlesmithjr/ansible-kvm
    name: mrlesmithjr.kvm
    version: 77a16fd70952d1aafeb809c9b3ded6b7671bb55b

  - src: git+https://github.com/rootmout/ansible-kvm.git
    name: rootmout.kvm
    version: 7cad2bc4e59cadd8de6cd20e4bb07fccdfdb2b1e

  - src: git+https://github.com/robertdebock/ansible-role-grub.git
    name: robertdebock.grub
    version: 1a7ee3bb11c927af77d5db492fbcfbba590b8ad5

  - src: git+https://github.com/PyratLabs/ansible-role-k3s.git
    name: xanmanning.k3s
    version: 19c24bd50381d06bac105ed7e9d012d73e46bef4 # 3.4.4

  - src: git+https://github.com/logan2211/ansible-bird.git
    name: logan2211.bird
    version: 904e55d56f82f36e3e9e9fbc5b3bd932a1151f7b # 1.9.0

  - srd: git+https://github.com/mrlesmithjr/ansible-nfs-server.git
    name: mrlesmithjr.nfs-server
    version: f35ec754c804c608d6adc610fc2664511ef66643
