---
- name: Install aptitude using apt (Debian)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: aptitude
    state: latest  # noqa package-latest
    update_cache: true
    force_apt_get: true

- name: Install common tools (Debian)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    update_cache: true
    state: present
    name:
      - iptables-persistent
