---
setup_type: "client"

# Client configuration.
client_wireguard_ip: 192.168.10.3/24
# The private cloud network.  Can also be a comma-separated list.
client_accessible_ips: "192.168.10.0/24"

# Server configuration.
server_public_ip: gate-1.ovh.infra.mout.ch
server_public_key: "{{ lookup('community.hashi_vault.hashi_vault', 'mout.ch/data/wireguard/gate-1.ovh.infra.mout.ch', validate_certs=false)['public_key'] }}"

netplan_enabled: true
netplan_configuration:
  network:
    version: 2
    ethernets:
      eth0:
        addresses:
          - 192.168.21.1/24
        nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
