---
- hosts: all
  tags: fqdn
  tasks:
    - name: "Set hostname"
      ansible.builtin.hostname:
        name: "{{ fqdn }}"

- hosts: all
  roles:
    - cri.bootstrap
  tags:
    - bootstrap

- hosts: all
  gather_facts: true
  tags:
    - "always"
    - "gather_facts"

- hosts: all
  roles:
    - role: common
  tags:
    - common

- hosts: all
  roles:
    - role: cri.common
      tags:
        - common
    - role: cri.network
      tags:
        - network
  vars_files:
    - ../vars/ssh_keys.yml

- hosts: all:!ceph
  tags: node-exporter
  roles:
    - cloudalchemy.node_exporter

#- hosts: consul
#  tags: consul
#  roles:
#    - ansible-consul
#
#- hosts: consul
#  tags: dns
#  roles:
#    - dns

- hosts: vault
  roles:
    - ansible-community.ansible-vault
  tags: vault

- hosts: gate
  tags: ip_forward
  tasks:
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

- hosts: vpn
  roles:
    - consensus.wireguard_cloud_gateway
  tags: vpn

- hosts: all
  any_errors_fatal: true
  tags: netplan
  roles:
    - role: mrlesmithjr.netplan
      become: yes

- hosts: ceph
  tags: docker
  roles:
    - cri.docker

- hosts: ceph
  tags: chrony
  roles:
    - mrlesmithjr.chrony

- hosts: ceph
  tags: cephadm
  roles:
    - cri.ceph_tools

- import_playbook: iptables.yaml

- hosts: compute-2.blotzheim.infra.mout.ch
  tags: [k3s-cache, k3s]
  tasks:
    - name: Create Partition on /dev/vdb
      parted:
        number: 1
        device: /dev/vdb
        state: present
        part_type: primary
        fs_type: ext4
      register: create_partition_result

    - name: Format Partition with ext4
      command: mkfs.ext4 /dev/vdb1
      when: create_partition_result.changed

    - name: Ensure k3s db Directory Exists
      file:
        path: "{{ k3s_db_path }}"
        state: directory
      become: yes  # Use sudo to create the directory if needed

    - name: Mount Partition to k3s directory
      mount:
        path: "{{ k3s_db_path }}"
        src: /dev/vdb1
        fstype: ext4
        state: mounted
        opts: defaults

- hosts: k3s
  tags: k3s
  roles:
     - role: xanmanning.k3s

- hosts: under-1.infra.mout.ch
  tags: k3s
  vars:
    k3s_release_version: latest
  roles:
     - role: xanmanning.k3s

- hosts: gate-1.blotzheim.infra.mout.ch
  tags: ddns
  roles:
    - role: maxhoesel.ddclient

# LVM
- hosts: hypervisor
  tags: lvm
  roles:
    - role: mrlesmithjr.lvm

# RAID
- hosts: hypervisor
  tags: mdadm
  roles:
    - role: mrlesmithjr.mdadm

# KVM
- hosts: hypervisor
  tags: kvm
  roles:
    - role: rootmout.kvm
  vars_files:
    - ../vars/ssh_keys.yml

# GRUB
- hosts: all
  tags: grub
  roles:
    - role: robertdebock.grub
