---

- hosts: all
  roles:
    - cri.bootstrap
  tags:
    - bootstrap

- hosts: all
  gather_facts: true
  tags:
    - "always"
    - "gather_facts"

- hosts: all
  roles:
    - role: common
  tags:
    - common

- hosts: all
  roles:
    - role: cri.common
      tags:
        - common
    - role: cri.network
      tags:
        - network
  vars_files:
    - ../vars/ssh_keys.yml

- hosts: all:!ceph
  tags: node-exporter
  roles:
    - cloudalchemy.node_exporter

- hosts: consul
  tags: consul
  roles:
    - ansible-consul

- hosts: consul
  tags: dns
  roles:
    - dns

- hosts: vault
  roles:
    - ansible-community.ansible-vault
  tags: vault

- hosts: gate
  tags: ip_forward
  tasks:
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

- hosts: vpn
  roles:
    - consensus.wireguard_cloud_gateway
  tags: vpn

- hosts: all
  any_errors_fatal: true
  tags: netplan
  roles:
    - role: mrlesmithjr.netplan
      become: yes

- hosts: ceph
  tags: docker
  roles:
    - cri.docker

- hosts: ceph
  tags: cephadm
  roles:
    - cri.ceph_tools

- hosts: gate-1.hirsingue.infra.mout.ch
  tags: iptables
  tasks:
    - name: nat traffic from 192.168.11.0/24 that doesnt reach vpn
      iptables:
        table: nat
        chain: POSTROUTING
        destination: "!192.168.10.0/24"
        jump: MASQUERADE

    - name: enable 192.168.11.0/24 to internet traffic
      iptables:
        chain: FORWARD
        source: 192.168.11.0/24
        jump: ACCEPT

    - name: enable internet 192.168.11.0/24 traffic
      iptables:
        chain: FORWARD
        destination: 192.168.11.0/24
        jump: ACCEPT

    - name: Save current state of the firewall in system file
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

- hosts: compute-1.hirsingue.infra.mout.ch
  tags: k3s
  vars:
    k3s_release_version: latest
  roles:
     - role: xanmanning.k3s

- hosts: under-1.infra.mout.ch
  tags: k3s
  vars:
    k3s_release_version: latest
  roles:
     - role: xanmanning.k3s
