---
- name: configure interfaces
  hosts: vyos
  connection: network_cli
  tasks:

    - name: enable SSH
      vyos.vyos.vyos_config:
        lines:
          - set service ssh port '22'
          - set service ssh disable-password-authentication
          - set service ssh loglevel info
          - set service ssh dynamic-protection
          - set service ssh dynamic-protection detect-time 3600

    - name: configure interfaces L2 settings
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet {{ item.name }} hw-id '{{ item.mac }}'
          - set interfaces ethernet {{ item.name }} description '{{ item.description }}'
          - set interfaces ethernet {{ item.name }} mtu '{{ item.mtu }}'
      loop: "{{ vyos_interfaces }}"

    - name: configure interfaces L3 settings
      vyos.vyos.vyos_l3_interfaces:
        config:
        - name: "{{ item.name }}"
          ipv4:
          - address: "{{ item.addresse }}"
        state: merged
      loop: "{{ vyos_interfaces }}"

    - name: configure DHCP for public network
      vyos.vyos.vyos_config:
        lines:
          - set service dhcp-server shared-network-name 'public' subnet 192.168.2.0/24 default-router '192.168.2.1'
          - set service dhcp-server shared-network-name 'public' subnet 192.168.2.0/24 name-server '192.168.2.1'
          - set service dhcp-server shared-network-name 'public' subnet 192.168.2.0/24 domain-name 'public-network'
          - set service dhcp-server shared-network-name 'public' subnet 192.168.2.0/24 lease '86400'
          - set service dhcp-server shared-network-name 'public' subnet 192.168.2.0/24 range 0 start '192.168.2.100'
          - set service dhcp-server shared-network-name 'public' subnet 192.168.2.0/24 range 0 stop '192.168.2.254'

    - name: configure source NAT for LAN & public network
      vyos.vyos.vyos_config:
        lines:
          - set nat source rule 100 outbound-interface 'eth0'
          - set nat source rule 100 source address '192.168.2.0/24'   # public
          - set nat source rule 100 translation address masquerade
          - set nat source rule 200 outbound-interface 'eth0'
          - set nat source rule 200 source address '192.168.14.0/24'  # lan
          - set nat source rule 200 translation address masquerade

    - name: configure DNS
      vyos.vyos.vyos_config:
        lines:
          - set service dns forwarding cache-size '0'
          - set service dns forwarding allow-from '192.168.0.0/16'
          - set service dns forwarding listen-address '192.168.2.1'
          - set service dns forwarding listen-address '192.168.13.1'
          - set service dns forwarding listen-address '192.168.14.1'
          - set service dns forwarding listen-address '192.168.15.1'
          - set service dns forwarding name-server '8.8.8.8'
          - set service dns forwarding name-server '8.8.4.4'

    - name: configure reverse proxy
      vyos.vyos.vyos_config:
        lines:
          - set load-balancing reverse-proxy service http port '80'
          - set load-balancing reverse-proxy service http redirect-http-to-https

          - set load-balancing reverse-proxy service https mode 'tcp'
          - set load-balancing reverse-proxy service https port '443'
          - set load-balancing reverse-proxy service https backend 'k3s-https'
          - set load-balancing reverse-proxy backend k3s-https mode 'tcp'
          - set load-balancing reverse-proxy backend k3s-https balance 'source-address'
          - set load-balancing reverse-proxy backend k3s-https server compute-2 address '192.168.13.11'
          - set load-balancing reverse-proxy backend k3s-https server compute-2 port '443'
          - set load-balancing reverse-proxy backend k3s-https server compute-2 check

          - set load-balancing reverse-proxy service kubectl mode 'tcp'
          - set load-balancing reverse-proxy service kubectl port '6443'
          - set load-balancing reverse-proxy service kubectl backend 'k3s-api'
          - set load-balancing reverse-proxy backend k3s-api mode 'tcp'
          - set load-balancing reverse-proxy backend k3s-api balance 'source-address'
          - set load-balancing reverse-proxy backend k3s-api server compute-2 address '192.168.13.11'
          - set load-balancing reverse-proxy backend k3s-api server compute-2 port '6443'
          - set load-balancing reverse-proxy backend k3s-api server compute-2 check

    - name: create group objects
      vyos.vyos.vyos_config:
        lines:
          - set firewall group network-group NET-WAN network '192.168.1.0/24'
          - set firewall group network-group NET-PUBLIC network '192.168.2.0/24'
          - set firewall group network-group NET-DMZ network '192.168.13.0/24'
          - set firewall group network-group NET-LAN network '192.168.14.0/24'
          - set firewall group network-group NET-CEPH network '192.168.15.0/24'
          - set firewall group network-group NET-MANAGEMENT network '192.168.1.1/32'
          - set firewall group network-group NET-MANAGEMENT network '192.168.1.100/32'

          - set firewall name WAN-LOCAL default-action 'drop'

          - set firewall name WAN-LOCAL rule 1010 action 'accept'
          - set firewall name WAN-LOCAL rule 1010 state established 'enable'
          - set firewall name WAN-LOCAL rule 1010 state related 'enable'

          - set firewall name WAN-LOCAL rule 1011 action 'drop'
          - set firewall name WAN-LOCAL rule 1011 state invalid 'enable'

          - set firewall name WAN-LOCAL rule 1020 action 'accept'
          - set firewall name WAN-LOCAL rule 1020 icmp type-name 'echo-request'
          - set firewall name WAN-LOCAL rule 1020 protocol 'icmp'
          - set firewall name WAN-LOCAL rule 1020 state new 'enable'

          # - set firewall name WAN-LOCAL rule 1110 action 'accept'
          # - set firewall name WAN-LOCAL rule 1110 destination port '161'
          # - set firewall name WAN-LOCAL rule 1110 protocol 'udp'
          # - set firewall name WAN-LOCAL rule 1110 source group network-group 'NET-MANAGEMENT'
          # - set firewall name WAN-LOCAL rule 1110 state new 'enable'

          - set firewall name WAN-LOCAL rule 1100 action 'drop'
          - set firewall name WAN-LOCAL rule 1100 destination port '22'
          - set firewall name WAN-LOCAL rule 1100 protocol 'tcp'
          - set firewall name WAN-LOCAL rule 1100 recent count '4'
          - set firewall name WAN-LOCAL rule 1100 recent time 'minute'
          # - set firewall name WAN-LOCAL rule 1100 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1100 state new 'enable'

          - set firewall name WAN-LOCAL rule 1101 action 'accept'
          - set firewall name WAN-LOCAL rule 1101 destination port '22'
          - set firewall name WAN-LOCAL rule 1101 protocol 'tcp'
          # - set firewall name WAN-LOCAL rule 1101 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1101 state new 'enable'

          - set firewall name WAN-LOCAL rule 1200 action 'drop'
          - set firewall name WAN-LOCAL rule 1200 destination port '80'
          - set firewall name WAN-LOCAL rule 1200 protocol 'tcp'
          - set firewall name WAN-LOCAL rule 1200 recent count '10'
          - set firewall name WAN-LOCAL rule 1200 recent time 'minute'
          # - set firewall name WAN-LOCAL rule 1200 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1200 state new 'enable'

          - set firewall name WAN-LOCAL rule 1201 action 'accept'
          - set firewall name WAN-LOCAL rule 1201 destination port '80'
          - set firewall name WAN-LOCAL rule 1201 protocol 'tcp'
          # - set firewall name WAN-LOCAL rule 1201 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1201 state new 'enable'

          - set firewall name WAN-LOCAL rule 1300 action 'drop'
          - set firewall name WAN-LOCAL rule 1300 destination port '443'
          - set firewall name WAN-LOCAL rule 1300 protocol 'tcp'
          - set firewall name WAN-LOCAL rule 1300 recent count '10'
          - set firewall name WAN-LOCAL rule 1300 recent time 'minute'
          # - set firewall name WAN-LOCAL rule 1300 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1300 state new 'enable'

          - set firewall name WAN-LOCAL rule 1301 action 'accept'
          - set firewall name WAN-LOCAL rule 1301 destination port '443'
          - set firewall name WAN-LOCAL rule 1301 protocol 'tcp'
          # - set firewall name WAN-LOCAL rule 1301 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1301 state new 'enable'

          - set firewall name WAN-LOCAL rule 1400 action 'drop'
          - set firewall name WAN-LOCAL rule 1400 destination port '6443'
          - set firewall name WAN-LOCAL rule 1400 protocol 'tcp'
          - set firewall name WAN-LOCAL rule 1400 recent count '4'
          - set firewall name WAN-LOCAL rule 1400 recent time 'minute'
          # - set firewall name WAN-LOCAL rule 1400 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1400 state new 'enable'

          - set firewall name WAN-LOCAL rule 1401 action 'accept'
          - set firewall name WAN-LOCAL rule 1401 destination port '6443'
          - set firewall name WAN-LOCAL rule 1401 protocol 'tcp'
          # - set firewall name WAN-LOCAL rule 1401 source group network-group 'NET-MANAGEMENT'
          - set firewall name WAN-LOCAL rule 1401 state new 'enable'

          - set firewall name LAN-LOCAL default-action 'drop'

          - set firewall name LAN-LOCAL rule 1010 action 'accept'
          - set firewall name LAN-LOCAL rule 1010 state established 'enable'
          - set firewall name LAN-LOCAL rule 1010 state related 'enable'

          - set firewall name LAN-LOCAL rule 1011 action 'drop'
          - set firewall name LAN-LOCAL rule 1011 state invalid 'enable'

          - set firewall name LAN-LOCAL rule 1020 action 'accept'
          - set firewall name LAN-LOCAL rule 1020 icmp type-name 'echo-request'
          - set firewall name LAN-LOCAL rule 1020 protocol 'icmp'
          - set firewall name LAN-LOCAL rule 1020 state new 'enable'

          - set firewall name LAN-LOCAL rule 1030 action 'accept'
          - set firewall name LAN-LOCAL rule 1030 destination port '67'
          - set firewall name LAN-LOCAL rule 1030 protocol 'udp'
          - set firewall name LAN-LOCAL rule 1030 state new 'enable'

          - set firewall name LAN-LOCAL rule 1040 action 'accept'
          - set firewall name LAN-LOCAL rule 1040 destination port '53'
          - set firewall name LAN-LOCAL rule 1040 protocol 'tcp_udp'
          - set firewall name LAN-LOCAL rule 1040 state new 'enable'

          # - set firewall name LAN-LOCAL rule 1100 action 'drop'
          # - set firewall name LAN-LOCAL rule 1100 destination port '22'
          # - set firewall name LAN-LOCAL rule 1100 protocol 'tcp'
          # - set firewall name LAN-LOCAL rule 1100 recent count '4'
          # - set firewall name LAN-LOCAL rule 1100 recent time 'minute'
          # - set firewall name LAN-LOCAL rule 1100 source group network-group 'NET-MANAGEMENT'
          # - set firewall name LAN-LOCAL rule 1100 state new 'enable'

          # - set firewall name LAN-LOCAL rule 1101 action 'accept'
          # - set firewall name LAN-LOCAL rule 1101 destination port '22'
          # - set firewall name LAN-LOCAL rule 1101 protocol 'tcp'
          # - set firewall name LAN-LOCAL rule 1101 source group network-group 'NET-MANAGEMENT'
          # - set firewall name LAN-LOCAL rule 1101 state new 'enable'

          # - set firewall name LAN-LOCAL rule 1110 action 'accept'
          # - set firewall name LAN-LOCAL rule 1110 destination port '161'
          # - set firewall name LAN-LOCAL rule 1110 protocol 'udp'
          # - set firewall name LAN-LOCAL rule 1110 source group network-group 'NET-MANAGEMENT'
          # - set firewall name LAN-LOCAL rule 1110 state new 'enable'


          - set firewall interface eth0 local name 'WAN-LOCAL'
          # - set interfaces ethernet eth1 firewall local name 'DMZ-LOCAL'
          - set firewall interface eth3 local name 'LAN-LOCAL'


          - set firewall name LAN-OUT default-action 'drop'

          - set firewall name LAN-OUT rule 1010 action 'accept'
          - set firewall name LAN-OUT rule 1010 state established 'enable'
          - set firewall name LAN-OUT rule 1010 state related 'enable'

          - set firewall name LAN-OUT rule 1011 action 'drop'
          - set firewall name LAN-OUT rule 1011 state invalid 'enable'

          - set firewall name LAN-OUT rule 1020 action 'accept'
          - set firewall name LAN-OUT rule 1020 icmp type-name 'echo-request'
          - set firewall name LAN-OUT rule 1020 protocol 'icmp'
          - set firewall name LAN-OUT rule 1020 state new 'enable'

          - set firewall interface eth3 out name 'LAN-OUT'
