---
# This role is strongly inspired from the ansible-vyos project
# See https://github.com/DreamLab/ansible-vyos
- name: Prepare dirs
  hosts: vyos
  gather_facts: no
  connection: local

  tasks:
    - name: Remove old compiled config
      file:
        path: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}"
        state: absent
      register: baseconfdir
      tags: build
      changed_when: False

    - name: Create empty compiled directory
      file:
        path: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}"
        state: directory
      tags: build
      changed_when: False

    - name: Remove old log directory
      file:
        path: "{{ playbook_dir }}/logs/{{ inventory_hostname }}"
        state: absent
      register: baselogdir
      tags: build
      changed_when: False

    - name: Create empty log dir
      file:
        path: "{{ playbook_dir }}/logs/{{ inventory_hostname }}"
        state: directory
      tags: build
      changed_when: False

    - name: Static configs directory
      file:
        path: "{{ playbook_dir }}/staticfiles"
        state: directory
      register: basestaticdir
      tags: build
      changed_when: False

    - name: Create empty diff directory
      file:
        path: "{{ playbook_dir }}/diff"
        state: directory
      tags: build
      changed_when: False
      when: ansible_diff_mode | bool


- name: Generate configs for vyos
  hosts: vyos
  gather_facts: no
  connection: local
  tags: build
  vars_files:
    - ../vars/ssh_keys.yml

  roles:
    - vyos/system
    - vyos/nat
    - vyos/firewall
    - vyos/interfaces
    - vyos/load_balancing


- name: Assemble and Generate configuration
  hosts: vyos
  connection: local
  gather_facts: no
  tags: compile

  tasks:
    - name: Assemble configuration
      assemble:
        src: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}"
        dest: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}/running.conf"
      changed_when: False


- name: Check version of VyOS
  hosts: vyos
  gather_facts: no
  tags: build

  tasks:
    - name: Check if FRR directory exists.
      stat:
        path: /etc/frr/
      register: vyos_frr_daemon


- name: Sent configuration to the device
  hosts: vyos
  connection: network_cli

  tasks:
    - name: Load Config, Diff ({{ ansible_diff_mode }}), Commit ({{ ansible_check_mode }})
      napalm.napalm.napalm_install_config:
        dev_os: 'vyos'
        config_file: "compiled/{{inventory_hostname}}/running.conf"
        commit_changes: "{{ not ansible_check_mode | bool }}"
        replace_config: true
        get_diffs: "{{ ansible_diff_mode | bool }}"
        diff_file: "{{ playbook_dir }}/diff/{{inventory_hostname}}.diff"
        hostname: "{{ inventory_hostname }}"
        username: "vyos"
        optional_args:
          verbose: true
          allow_agent: true
      delegate_to: localhost


# This step is important to be sure that the secrets, gathered by the vault
# lookup plugin, stay not on the machine.
# TODO: make the cleanup always run, even if the playbook fails
- name: Cleanup generated config
  hosts: vyos
  gather_facts: no
  connection: local

  tasks:
    - name: Remove config
      file:
        path: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}"
        state: absent
      register: baseconfdir
      tags: build
      changed_when: False
